source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'CFExtension_Example' do
  pod 'CFExtension', :path => '../'

  target 'CFExtension_Tests' do
    inherit! :search_paths

    
  end
end
